import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Calendar, AlertTriangle } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface AITenantSummaryModalProps {
  aiSummary?: string;
  aiAnalysis?: string;
  lastAnalysisDate?: string;
  tenantName: string;
  children?: React.ReactNode;
}

export function AITenantSummaryModal({
  aiSummary,
  aiAnalysis,
  lastAnalysisDate,
  tenantName,
  children,
}: AITenantSummaryModalProps) {
  if (!aiSummary && !aiAnalysis) {
    return null;
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        {children || (
          <Button variant="outline" size="sm" className="rounded-full">
            <Sparkles className="w-4 h-4 mr-2" />
            AI Summary
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[700px] max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            <DialogTitle>AI-Generated Tenant Analysis</DialogTitle>
          </div>
          <DialogDescription>
            Analysis for {tenantName}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Warning Banner */}
          <Card className="border-amber-200 bg-amber-50 dark:bg-amber-950/20">
            <CardContent className="p-4">
              <div className="flex gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <p className="text-sm font-medium text-amber-900 dark:text-amber-200">
                    AI-Generated Content
                  </p>
                  <p className="text-xs text-amber-700 dark:text-amber-300">
                    This analysis is automatically generated by AI based on the tenant's documents and information.
                    Please use this as a supplementary tool and conduct your own due diligence.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Last Analysis Date */}
          {lastAnalysisDate && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Calendar className="w-4 h-4" />
              <span>Last analyzed: {new Date(lastAnalysisDate).toLocaleString()}</span>
            </div>
          )}

          {/* AI Summary */}
          {aiSummary && (
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="rounded-full">
                  Summary
                </Badge>
              </div>
              <Card className="border-none shadow-sm bg-muted/50">
                <CardContent className="p-4">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {aiSummary}
                  </p>
                </CardContent>
              </Card>
            </div>
          )}

          {/* AI Analysis */}
          {aiAnalysis && (
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="rounded-full">
                  Detailed Analysis
                </Badge>
              </div>
              <Card className="border-none shadow-sm bg-muted/50">
                <CardContent className="p-4">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {aiAnalysis}
                  </p>
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
